# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Topology for Data Science
email: benjamin.holmgren1@students.montana.edu
description: >- # this means to ignore newlines until "baseurl:"
  Various tutorials on important techniques in topological data analysis.
  Tutorials made with the final goal in mind to use the R package TDA in
  order to actually implement each technique.
baseurl: /rpackage_tutorials/
url: https://comptag.github.io
github_username:  benholmgren
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
theme: jekyll-swiss
urlimg: /images/
plugins:
  - jekyll-feed

# scholar:
#   style: mla

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
